### ISSUE TITLE
Add ASUS ROG PUGIO II 

### ISSUE THREAD

**Issue by AshFungor** [denilsonsa/udev-joystick-blacklist#55]
So, the issue is simple, would be nice to have it supported.
If I didn't miss anything of course, at least with mine it doesn't work.

**Comment by denilsonsa** [comment]
Sorry for the long delay.

You have not given me the vendorId and the productId of your device. How would I be able to add it if you don't tell me the ids? ;)

Also, this repository is not about adding support for things.

I'm closing this due to lack of enough information. Please feel free to reopen if you can provide us with [relevant data](https://github.com/denilsonsa/udev-joystick-blacklist#contributing).
