### ISSUE TITLE
Cideko air keyboard

### ISSUE THREAD

**Issue by MCS1974** [denilsonsa/udev-joystick-blacklist#57]
As per this post:
https://askubuntu.com/questions/1484990/cideko-air-keyboard-being-recognised-as-a-joystick-22-04

Cideko Air Keyboard is recognised as a joystick.  The keyboard/mouse functionality only works when the joystick calibration screen is running.

Tried to use the /etc/udev/rules.d/51-these-are-not-joysticks.rules and it doesn't make any difference.  Using the /etc/udev/rules.d/51-these-are-not-joysticks-rm.rules removes it altogether, such that the "joystick" does not appear in the calibration screen, but neither does it work as mouse/keyboard as intended.

Something I'm doing wrong?

**Comment by denilsonsa** [comment]
Without having the device, it's hard to know. And the company doesn't even exist anymore, as their website is gone [since 2016](https://web.archive.org/web/20160412151519/http://www.cideko.com/product.php?cat_id=20): <http://www.cideko.com/pro_con.php?id=15>

Your issue sounds unrelated to this repository, as your issue is the main keyboard/mouse functionality stopped working recently, and it only works while the joystick calibration is running. (I'm assuming it would also work if any app or game starts using the joystick, like when opening [this test page](https://greggman.github.io/html5-gamepad-test/).)

I'm closing this issue here, as it's not related to this repository. Good luck!
